POST http://localhost:3333/transactions HTTP/1.1
content-type: application/json

{
    "title": "Bico",
    "amount": 8000,
    "type": "credit"
}

### ---------------------------------------------

GET http://localhost:3333/transactions HTTP/1.1
content-type: application/json

### ---------------------------------------------

GET http://localhost:3333/transactions/cbab514b-1d4f-467a-acfc-2d67423c16d6 HTTP/1.1
content-type: application/json


### ---------------------------------------------

GET http://localhost:3333/transactions/summary HTTP/1.1
content-type: application/json